"use strict";

const EPSILON = 1e-10;
const tools = [
  {id:"returns",number:"01",title:"報酬與現金流",subtitle:"投資績效核心計算",tags:["IRR","XIRR","NPV","CAGR","ROI","年化報酬","實質報酬","稅後報酬"]},
  {id:"growth",number:"02",title:"複利與投入規劃",subtitle:"資產成長與目標投入",tags:["複利終值","現值","定期定額","單筆投資","配息再投入","損益兩平","反推投入"]},
  {id:"policy",number:"03",title:"保單價值分析",subtitle:"保費與保單價值現金流",tags:["保單年度 IRR","解約金 IRR","保障槓桿","累積保費","保單損益兩平"]},
  {id:"retirement",number:"04",title:"年金與退休規劃",subtitle:"退休準備與資金缺口",tags:["年金現值","年金終值","退休金缺口","通膨"]},
  {id:"risk",number:"05",title:"投資風險指標",subtitle:"報酬序列與風險品質",tags:["標準差","夏普值","Beta","Alpha","R²","最大回撤","波動率","風險報酬比較"]},
  {id:"loan",number:"06",title:"貸款與分期",subtitle:"借款成本與提前還款",tags:["本息攤還","房貸","提前還款","貸款比較","分期實質利率","循環利息"]},
  {id:"currency",number:"07",title:"匯率與稅後報酬",subtitle:"匯兌與稅負試算",tags:["匯率損益","稅後報酬","配息所得稅"]},
  {id:"cashflow",number:"08",title:"現金流與資產配置",subtitle:"結餘、配置與組合報酬",tags:["每月現金流","儲蓄率","資產配置","投資組合報酬","帳戶餘額"]}
];

const $ = (selector, root=document) => root.querySelector(selector);
const n = (value, fallback=0) => { const parsed=Number(String(value).replace(/,/g,"").trim()); return Number.isFinite(parsed)?parsed:fallback; };
const val = id => n($("#"+id)?.value, Number.NaN);
const raw = id => $("#"+id)?.value || "";
const pct = value => Number.isFinite(value)?`${(value*100).toFixed(2)}%`:"無法計算";
const num = (value,digits=2) => Number.isFinite(value)?new Intl.NumberFormat("zh-TW",{maximumFractionDigits:digits}).format(value):"無法計算";
const money = (value,digits=0) => Number.isFinite(value)?new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:digits}).format(value):"無法計算";
const parseCashflows = text => text.split(/[\n,，;；]+/).map(x=>n(x,Number.NaN)).filter(Number.isFinite);
const parseSeries = text => text.split(/[\n,，;；\s]+/).map(x=>n(x,Number.NaN)).filter(Number.isFinite).map(x=>x/100);
const parseDated = text => text.split(/\n+/).map(line=>{const [date,amount]=line.split(/[|｜,，\t]+/).map(x=>x.trim());return{date:new Date(date),amount:n(amount,Number.NaN)}}).filter(x=>!Number.isNaN(x.date.getTime())&&Number.isFinite(x.amount));
const average = a => a.length?a.reduce((s,x)=>s+x,0)/a.length:Number.NaN;
const std = a => {if(a.length<2)return Number.NaN;const m=average(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1));};
const covariance = (a,b) => {const count=Math.min(a.length,b.length);if(count<2)return Number.NaN;const x=a.slice(0,count),y=b.slice(0,count),xm=average(x),ym=average(y);return x.reduce((s,v,i)=>s+(v-xm)*(y[i]-ym),0)/(count-1);};
const correlation = (a,b) => {const count=Math.min(a.length,b.length),den=std(a.slice(0,count))*std(b.slice(0,count));return den?covariance(a.slice(0,count),b.slice(0,count))/den:Number.NaN;};
const npv = (rate,flows) => rate<=-1||!flows.length?Number.NaN:flows.reduce((s,x,i)=>s+x/(1+rate)**i,0);
const irr = flows => {
  if(flows.length<2||!flows.some(x=>x<0)||!flows.some(x=>x>0))return Number.NaN;
  let low=-.9999,high=10,lv=npv(low,flows),hv=npv(high,flows);
  for(let i=0;i<12&&lv*hv>0;i++){high*=2;hv=npv(high,flows)}
  if(!Number.isFinite(lv)||!Number.isFinite(hv)||lv*hv>0)return Number.NaN;
  for(let i=0;i<220;i++){const mid=(low+high)/2,v=npv(mid,flows);if(Math.abs(v)<EPSILON)return mid;if(lv*v<=0)high=mid;else{low=mid;lv=v}}
  return (low+high)/2;
};
const xnpv = (rate,flows) => {if(rate<=-1||!flows.length)return Number.NaN;const first=flows[0].date.getTime();return flows.reduce((s,x)=>s+x.amount/(1+rate)**((x.date.getTime()-first)/86400000/365),0)};
const xirr = flows => {if(flows.length<2||!flows.some(x=>x.amount<0)||!flows.some(x=>x.amount>0))return Number.NaN;const sorted=[...flows].sort((a,b)=>a.date-b.date);let low=-.9999,high=10,lv=xnpv(low,sorted),hv=xnpv(high,sorted);for(let i=0;i<12&&lv*hv>0;i++){high*=2;hv=xnpv(high,sorted)}if(!Number.isFinite(lv)||!Number.isFinite(hv)||lv*hv>0)return Number.NaN;for(let i=0;i<220;i++){const mid=(low+high)/2,v=xnpv(mid,sorted);if(Math.abs(v)<EPSILON)return mid;if(lv*v<=0)high=mid;else{low=mid;lv=v}}return(low+high)/2};
const futureValue=(principal,monthly,annualRate,years)=>{const periods=Math.max(0,Math.round(years*12)),r=annualRate/12;return principal*(1+r)**periods+(Math.abs(r)<EPSILON?monthly*periods:monthly*((1+r)**periods-1)/r)};
const presentValue=(future,rate,years)=>future/(1+rate)**years;
const monthlyForTarget=(target,principal,rate,years)=>{const periods=Math.max(1,Math.round(years*12)),r=rate/12,grown=principal*(1+r)**periods;return Math.abs(r)<EPSILON?(target-grown)/periods:(target-grown)*r/((1+r)**periods-1)};
const yearsToTarget=(target,principal,monthly,rate)=>{if(target<=principal)return 0;for(let month=1;month<=1200;month++)if(futureValue(principal,monthly,rate,month/12)>=target)return month/12;return Number.NaN};
const payment=(principal,rate,months)=>{const count=Math.max(1,Math.round(months)),r=rate/12;return Math.abs(r)<EPSILON?principal/count:principal*r/(1-(1+r)**-count)};
const amortize=(principal,rate,months,extra=0)=>{const scheduled=payment(principal,rate,months),r=rate/12;let balance=principal,totalInterest=0,count=0;while(balance>.01&&count<2400){const interest=balance*r,paid=Math.min(balance+interest,scheduled+Math.max(0,extra));balance=Math.max(0,balance+interest-paid);totalInterest+=interest;count++}return{scheduled,months:count,totalInterest,totalPaid:principal+totalInterest}};
const maxDrawdown=returns=>{let value=1,peak=1,drawdown=0;returns.forEach(r=>{value*=1+r;peak=Math.max(peak,value);drawdown=Math.min(drawdown,value/peak-1)});return drawdown};

const field=(id,label,value,suffix="",hint="")=>`<label class="field"><span>${label}</span><div class="input-wrap"><input id="${id}" type="number" inputmode="decimal" value="${value}">${suffix?`<b>${suffix}</b>`:""}</div>${hint?`<small>${hint}</small>`:""}</label>`;
const area=(id,label,value,hint="")=>`<label class="field wide"><span>${label}</span><textarea id="${id}" rows="5">${value}</textarea>${hint?`<small>${hint}</small>`:""}</label>`;
const result=(id,label,note="")=>`<article class="result-card"><span>${label}</span><strong id="${id}">—</strong>${note?`<small>${note}</small>`:""}</article>`;
const set=(id,value)=>{const node=$("#"+id);if(node)node.textContent=value};
const heading=(eyebrow,title,description)=>`<div class="panel-heading"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div><p>${description}</p></div>`;

const panels={
returns:{html:()=>`${heading("RETURN LAB","報酬與現金流","金額視為同一幣別；負數代表投入或支出，正數代表回收或收入。")}<div class="form-grid">${field("r-start","期初投入",100000,"元")}${field("r-end","期末價值",150000,"元")}${field("r-years","持有期間",5,"年")}${field("r-inflation","通膨率",2,"%")}${field("r-tax","稅率",10,"%")}${field("r-discount","NPV 折現率",5,"%")}</div><div class="results-grid">${result("r-roi","ROI 投資報酬率")}${result("r-cagr","CAGR／年化報酬率")}${result("r-real","通膨後實質報酬")}${result("r-after","簡化稅後報酬","正報酬乘上稅後比例")}</div><div class="split-input">${area("r-flows","等期間現金流","-100000, 20000, 25000, 30000, 35000, 40000","第一期通常為負數；以逗號分隔。")}<div class="mini-results">${result("r-irr","IRR 內部報酬率")}${result("r-npv","NPV 淨現值")}</div></div><div class="split-input">${area("r-dated","不定期現金流","2021-01-01｜-100000\n2022-06-30｜25000\n2024-03-15｜35000\n2026-01-01｜70000","每行：日期｜金額")}<div class="mini-results">${result("r-xirr","XIRR 不定期年化報酬")}${result("r-xstate","判讀")}</div></div>`,calc:()=>{const start=val("r-start"),end=val("r-end"),years=Math.max(.0001,val("r-years")),roi=start?(end-start)/start:Number.NaN,cagr=start>0&&end>=0?(end/start)**(1/years)-1:Number.NaN,real=(1+cagr)/(1+val("r-inflation")/100)-1,flows=parseCashflows(raw("r-flows")),xr=xirr(parseDated(raw("r-dated")));set("r-roi",pct(roi));set("r-cagr",pct(cagr));set("r-real",pct(real));set("r-after",pct(roi*(1-val("r-tax")/100)));set("r-irr",pct(irr(flows)));set("r-npv",money(npv(val("r-discount")/100,flows)));set("r-xirr",pct(xr));set("r-xstate",Number.isFinite(xr)?(xr>=0?"正報酬":"負報酬"):"請檢查現金流")}},
growth:{html:()=>`${heading("COMPOUND GROWTH","複利與投入規劃","假設報酬率固定且每月底投入；實際市場報酬不會固定。")}<div class="form-grid">${field("g-principal","目前本金",200000,"元")}${field("g-monthly","每月投入",10000,"元")}${field("g-rate","預期年報酬率",6,"%")}${field("g-dividend","配息率（全數再投入）",3,"%")}${field("g-years","投資期間",10,"年")}${field("g-target","目標金額",3000000,"元")}</div><div class="results-grid">${result("g-lump","單筆投資終值")}${result("g-total","定期定額終值")}${result("g-reinvest","配息再投入情境","以報酬率與配息率相加簡化估算")}${result("g-present","目標金額現在價值")}${result("g-monthly-need","達標所需每月投入")}${result("g-principal-need","達標所需期初本金")}${result("g-years-need","依目前投入達標時間")}${result("g-cost","預估投入本金")}</div>`,calc:()=>{const p=val("g-principal"),m=val("g-monthly"),r=val("g-rate")/100,d=val("g-dividend")/100,y=val("g-years"),t=val("g-target"),need=presentValue(t-futureValue(0,m,r,y),r,y),when=yearsToTarget(t,p,m,r);set("g-lump",money(futureValue(p,0,r,y)));set("g-total",money(futureValue(p,m,r,y)));set("g-reinvest",money(futureValue(p,m,r+d,y)));set("g-present",money(presentValue(t,r,y)));set("g-monthly-need",money(Math.max(0,monthlyForTarget(t,p,r,y))));set("g-principal-need",money(Math.max(0,need)));set("g-years-need",Number.isFinite(when)?`${num(when,1)} 年`:"超過 100 年／無法達標");set("g-cost",money(p+m*y*12))}},
policy:{html:()=>`${heading("POLICY VALUE","保單價值分析","依保單年度輸入保費與解約金；只做現金流試算，不代表商品建議。")}<div class="split-input">${area("p-premiums","每年度保費","100000,100000,100000,100000,100000,100000,100000,100000,100000,100000","依年度用逗號分隔")}${area("p-values","各年度末解約金／保單價值","20000,80000,160000,260000,380000,510000,650000,800000,960000,1130000","數量應與年度保費相近")}</div><div class="form-grid compact">${field("p-benefit","保障金額",3000000,"元")}</div><div class="results-grid">${result("p-paid","最新年度累積保費")}${result("p-value","最新解約金")}${result("p-irr","最新年度解約金 IRR")}${result("p-leverage","保障／累積保費倍數")}${result("p-break","解約金損益兩平年度")}</div><div class="table-wrap"><table><thead><tr><th>年度</th><th>累積保費</th><th>保單價值</th><th>年度 IRR</th></tr></thead><tbody id="p-table"></tbody></table></div>`,calc:()=>{const premiums=parseCashflows(raw("p-premiums")).map(Math.abs),values=parseCashflows(raw("p-values")),rows=values.map((value,i)=>{const paid=premiums.slice(0,i+1).reduce((s,x)=>s+x,0),flows=[0,...premiums.slice(0,i+1).map(x=>-x)];flows[flows.length-1]+=value;return{year:i+1,value,paid,rate:irr(flows)}}),latest=rows.at(-1),breakeven=rows.find(x=>x.value>=x.paid)?.year,leverage=latest?.paid?val("p-benefit")/latest.paid:Number.NaN;set("p-paid",money(latest?.paid));set("p-value",money(latest?.value));set("p-irr",pct(latest?.rate));set("p-leverage",Number.isFinite(leverage)?`${num(leverage)} 倍`:"無法計算");set("p-break",breakeven?`第 ${breakeven} 年`:"輸入期間內尚未達成");$("#p-table").innerHTML=rows.slice(0,30).map(x=>`<tr><td>第 ${x.year} 年</td><td>${money(x.paid)}</td><td>${money(x.value)}</td><td>${pct(x.rate)}</td></tr>`).join("")}},
retirement:{html:()=>`${heading("RETIREMENT MAP","年金與退休規劃","以實質報酬率估算退休支出現值，未納入稅負、醫療與市場順序風險。")}<div class="form-grid">${field("t-age","目前年齡",35,"歲")}${field("t-retire","預計退休年齡",65,"歲")}${field("t-life","規劃至年齡",90,"歲")}${field("t-saved","目前退休準備",500000,"元")}${field("t-monthly","每月投入",15000,"元")}${field("t-rate","預期年報酬率",5,"%")}${field("t-inflation","預期通膨率",2,"%")}${field("t-expense","目前每月生活費",40000,"元")}</div><div class="results-grid">${result("t-years","距離退休")}${result("t-after-years","退休後規劃期間")}${result("t-real","通膨後實質報酬率")}${result("t-future-expense","退休時每月生活費")}${result("t-projected","預估退休準備終值")}${result("t-needed","退休所需資金現值")}${result("t-gap","退休資金缺口")}${result("t-ready","準備完成度")}</div>`,calc:()=>{const years=Math.max(0,val("t-retire")-val("t-age")),after=Math.max(1,val("t-life")-val("t-retire")),r=val("t-rate")/100,i=val("t-inflation")/100,real=(1+r)/(1+i)-1,projected=futureValue(val("t-saved"),val("t-monthly"),r,years),expense=val("t-expense")*(1+i)**years,annual=expense*12,needed=Math.abs(real)<EPSILON?annual*after:annual*(1-(1+real)**-after)/real,gap=needed-projected;set("t-years",`${num(years,0)} 年`);set("t-after-years",`${num(after,0)} 年`);set("t-real",pct(real));set("t-future-expense",money(expense));set("t-projected",money(projected));set("t-needed",money(needed));set("t-gap",money(Math.max(0,gap)));set("t-ready",pct(needed?Math.min(1,projected/needed):Number.NaN))}},
risk:{html:()=>`${heading("RISK SIGNALS","投資風險指標","範例以每月報酬率計算；請輸入相同期間、相同頻率的資產與指標報酬。")}<div class="split-input">${area("k-asset","資產每月報酬率（%）","2.1,-1.2,3.4,0.8,-2.0,4.1,1.5,0.2,2.7,-0.6,1.8,2.2")}${area("k-market","比較指標每月報酬率（%）","1.7,-0.8,2.8,0.5,-1.5,3.2,1.1,0.1,2.0,-0.4,1.3,1.6")}</div><div class="form-grid compact">${field("k-rf","無風險利率",1.5,"%")}</div><div class="results-grid">${result("k-count","資料期數")}${result("k-return","估計年化報酬率")}${result("k-volatility","標準差／年化波動率")}${result("k-sharpe","夏普值")}${result("k-beta","Beta")}${result("k-alpha","Alpha")}${result("k-r2","R²")}${result("k-drawdown","最大回撤")}${result("k-score","風險報酬比")}${result("k-market-return","比較指標年化報酬")}</div>`,calc:()=>{const a=parseSeries(raw("k-asset")),b=parseSeries(raw("k-market")),mean=average(a),annual=(1+mean)**12-1,vol=std(a)*Math.sqrt(12),marketAnnual=(1+average(b))**12-1,variance=std(b)**2,beta=variance?covariance(a,b)/variance:Number.NaN,rf=val("k-rf")/100,alpha=annual-(rf+beta*(marketAnnual-rf)),corr=correlation(a,b);set("k-count",`${a.length} 期`);set("k-return",pct(annual));set("k-volatility",pct(vol));set("k-sharpe",num(vol?(annual-rf)/vol:Number.NaN));set("k-beta",num(beta));set("k-alpha",pct(alpha));set("k-r2",pct(corr*corr));set("k-drawdown",pct(maxDrawdown(a)));set("k-score",num(vol?annual/vol:Number.NaN));set("k-market-return",pct(marketAnnual))}},
loan:{html:()=>`${heading("DEBT LAB","貸款與分期","本息平均攤還採固定利率估算；實際費用仍應包含開辦費、帳管費與違約金。")}<div class="form-grid">${field("l-principal","貸款本金",5000000,"元")}${field("l-rate","貸款年利率",2.2,"%")}${field("l-months","貸款期數",360,"月")}${field("l-extra","每月額外還款",5000,"元")}${field("l-alt","比較方案年利率",2.6,"%")}</div><div class="results-grid">${result("l-payment","每月本息攤還")}${result("l-interest","原方案總利息")}${result("l-faster","額外還款後期數")}${result("l-save","預估節省利息")}${result("l-alt-payment","比較方案月付金")}${result("l-diff","兩方案月付差額")}</div><div class="subsection"><h3>分期付款實質利率</h3><div class="form-grid compact">${field("l-cash","現金價",100000,"元")}${field("l-total","分期總價",108000,"元")}${field("l-install-months","分期期數",12,"月")}</div><div class="results-grid">${result("l-install-rate","估計年化實質利率")}</div></div><div class="subsection"><h3>信用卡循環利息</h3><div class="form-grid compact">${field("l-card","循環餘額",50000,"元")}${field("l-card-rate","循環年利率",15,"%")}${field("l-days","計息天數",30,"天")}</div><div class="results-grid">${result("l-card-interest","本期估計循環利息")}</div></div>`,calc:()=>{const principal=val("l-principal"),rate=val("l-rate")/100,months=val("l-months"),base=amortize(principal,rate,months),faster=amortize(principal,rate,months,val("l-extra")),alt=payment(principal,val("l-alt")/100,months),count=Math.max(1,Math.round(val("l-install-months"))),monthly=val("l-total")/count,monthlyRate=irr([val("l-cash"),...Array.from({length:count},()=>-monthly)]),annualRate=(1+monthlyRate)**12-1,cardInterest=val("l-card")*val("l-card-rate")/100*val("l-days")/365;set("l-payment",money(base.scheduled));set("l-interest",money(base.totalInterest));set("l-faster",`${faster.months} 月`);set("l-save",money(base.totalInterest-faster.totalInterest));set("l-alt-payment",money(alt));set("l-diff",money(alt-base.scheduled));set("l-install-rate",pct(annualRate));set("l-card-interest",money(cardInterest))}},
currency:{html:()=>`${heading("FX & TAX","匯率與稅後報酬","稅額採自訂有效稅率簡化估算，不代表個人實際申報結果。")}<div class="form-grid">${field("c-amount","外幣金額",10000)}${field("c-buy","買入匯率",32)}${field("c-sell","賣出匯率",33)}${field("c-return","外幣資產報酬率",8,"%")}${field("c-tax","獲利有效稅率",20,"%")}</div><div class="results-grid">${result("c-cost","原始台幣成本")}${result("c-final","換回台幣價值")}${result("c-fx","純匯率損益")}${result("c-profit","合計損益")}${result("c-total-return","含匯率總報酬率")}${result("c-tax-value","估計稅額")}${result("c-after","稅後損益")}</div><div class="subsection"><h3>配息所得稅簡化試算</h3><div class="form-grid compact">${field("c-dividend","年度配息",100000,"元")}${field("c-dividend-tax","自訂有效稅率／抵減率",8.5,"%")}</div><div class="results-grid">${result("c-dividend-tax-value","估計稅額或抵減額")}${result("c-dividend-net","配息扣除後金額")}</div></div>`,calc:()=>{const foreign=val("c-amount"),cost=foreign*val("c-buy"),final=foreign*(1+val("c-return")/100)*val("c-sell"),profit=final-cost,tax=Math.max(0,profit)*val("c-tax")/100,divTax=val("c-dividend")*val("c-dividend-tax")/100;set("c-cost",money(cost));set("c-final",money(final));set("c-fx",money(foreign*(val("c-sell")-val("c-buy"))));set("c-profit",money(profit));set("c-total-return",pct(cost?profit/cost:Number.NaN));set("c-tax-value",money(tax));set("c-after",money(profit-tax));set("c-dividend-tax-value",money(divTax));set("c-dividend-net",money(val("c-dividend")-divTax))}},
cashflow:{html:()=>`${heading("CASH & ALLOCATION","現金流與資產配置","用每月收支與目前資產，確認儲蓄率、配置比例及再平衡差額。")}<div class="form-grid">${field("f-income","每月收入",70000,"元")}${field("f-fixed","固定支出",25000,"元")}${field("f-variable","變動支出",18000,"元")}${field("f-debt","貸款／分期支出",5000,"元")}</div><div class="results-grid">${result("f-net","每月可用現金流")}${result("f-rate","儲蓄率")}${result("f-total","目前總資產")}${result("f-return","投資組合預期報酬")}</div>${area("f-assets","資產配置","現金｜300000｜15｜1\n台股｜800000｜35｜7\n全球股票｜900000｜40｜8\n債券｜200000｜10｜3","每行：資產名稱｜目前金額｜目標比例%｜預期報酬率%") }<div class="table-wrap"><table><thead><tr><th>資產</th><th>目前比例</th><th>目標比例</th><th>建議調整</th></tr></thead><tbody id="f-table"></tbody></table></div>`,calc:()=>{const income=val("f-income"),net=income-val("f-fixed")-val("f-variable")-val("f-debt"),rows=raw("f-assets").split(/\n+/).map(line=>{const [name,value,target,expected]=line.split(/[|｜,，\t]+/).map(x=>x.trim());return{name,value:n(value,Number.NaN),target:n(target,Number.NaN)/100,expected:n(expected,Number.NaN)/100}}).filter(x=>x.name&&Number.isFinite(x.value)),total=rows.reduce((s,x)=>s+x.value,0),allocation=rows.map(x=>({...x,current:total?x.value/total:0,difference:x.target*total-x.value})),portfolio=allocation.reduce((s,x)=>s+x.current*(Number.isFinite(x.expected)?x.expected:0),0);set("f-net",money(net));set("f-rate",pct(income?net/income:Number.NaN));set("f-total",money(total));set("f-return",pct(portfolio));$("#f-table").innerHTML=allocation.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${pct(x.current)}</td><td>${pct(x.target)}</td><td class="${x.difference>=0?"positive":"negative"}">${x.difference>=0?"增加":"減少"} ${money(Math.abs(x.difference))}</td></tr>`).join("")}}
};

function escapeHtml(text){return String(text).replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[char])}
let active="returns";
function renderNav(query=""){
  const term=query.trim().toLowerCase();
  $("#tool-nav").innerHTML=tools.filter(tool=>(tool.title+tool.subtitle+tool.tags.join(" ")).toLowerCase().includes(term)).map(tool=>`<button type="button" data-tool="${tool.id}" class="${tool.id===active?"active":""}"><span>${tool.number}</span><div><strong>${tool.title}</strong><small>${tool.subtitle}</small></div></button>`).join("")||"<p>找不到符合的工具。</p>";
}
function renderPanel(){
  const tool=tools.find(item=>item.id===active);
  $("#calculator").innerHTML=`<div class="tool-tags">${tool.tags.map(tag=>`<span>${tag}</span>`).join("")}</div>${panels[active].html()}`;
  $("#calculator").oninput=panels[active].calc;
  panels[active].calc();
}
$("#tool-nav").addEventListener("click",event=>{const button=event.target.closest("button[data-tool]");if(!button)return;active=button.dataset.tool;renderNav($("#tool-search").value);renderPanel();if(window.innerWidth<1050)$("#calculator").scrollIntoView({behavior:"smooth",block:"start"})});
$("#tool-search").addEventListener("input",event=>renderNav(event.target.value));
renderNav();
renderPanel();
